### ISSUE TITLE
Undefined method beat

### ISSUE THREAD

**Issue by Jypotheren734x** [moleculer-ruby/moleculer#56]
```
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422 [2019-05-22T17:43:27.665+00:00] ERROR: [REDIS.TRANSPORTER.SUBSCRIPTION.MOL.HEARTBEAT] undefined method `beat' for nil:NilClass 
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/moleculer-0.1.1/lib/moleculer/broker.rb:305:in `block in subscribe_to_heartbeat'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/moleculer-0.1.1/lib/moleculer/transporters/redis.rb:125:in `process_packet'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/moleculer-0.1.1/lib/moleculer/transporters/redis.rb:84:in `block (3 levels) in connect'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/subscribe.rb:45:in `block in subscription'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:139:in `block (3 levels) in call_loop'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:133:in `loop'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:133:in `block (2 levels) in call_loop'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:229:in `block (2 levels) in process'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:366:in `ensure_connected'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:132:in `block in call_loop'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:278:in `with_socket_timeout'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:131:in `call_loop'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/subscribe.rb:43:in `subscription'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis/subscribe.rb:12:in `subscribe'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2824:in `_subscription'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2192:in `block in subscribe'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /usr/local/rbenv/versions/2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2191:in `subscribe'
2019-05-22T17:43:27Z service/progress:RXAQEVZVKZN/9fb0cc0eb422    /app/vendor/bundle/ruby/2.4.0/gems/moleculer-0.1.1/lib/moleculer/transporters/redis.rb:75:in `block in connect'
```

**Comment by Jypotheren734x** [comment]
When there are packets in redis from a destroyed node that are still hanging around, it seems to grab them and then that node isn't registered so the error is thrown
